const actionsTypesGetRandom = {
  LOADING_GET_RANDOM: "LOADING_GET_RANDOM",
  LOAD_SUCCESS_GET_RANDOM: "LOAD_SUCCESS_GET_RANDOM",
  LOAD_ERROR_GET_RANDOM: "LOAD_ERROR_GET_RANDOM"
};

export default actionsTypesGetRandom;
